### PR TITLE
fix(tasks): skip wiredeps per default

### LINKED ISSUE #1558: Builds based on `master` are broken due to incompatible diagram-js version
__Describe the Bug__

Our CI on branches targeting `master` is currently broken, cf. [this build](https://github.com/bpmn-io/bpmn-js/runs/4725608553?check_suite_focus=true#step:6:18).

It's working fine locally though.

__Steps to Reproduce__

1. Checkout [this build](https://github.com/bpmn-io/bpmn-js/runs/4725608553?check_suite_focus=true#step:6:18)
2. See the build is failing on 25 broken test cases

__Expected Behavior__

Make CI work again.

__Environment__

 - Browser: not specified
 - OS: discovered on Linux & Mac, Windows seem to work fine.
 - Library version: `master`

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Closes #1558 

Proof it works: https://github.com/bpmn-io/bpmn-js/runs/4726762563

### CODE REVIEW

**Comment by nikku** [comment]
Alternative to consider: Change the default branch to build against to master; we'll need to undo this change once bpmn-js@next-major-alpha is released; which is some day, soon.

**Comment by pinussilvestrus** [comment]
Thanks for your thoughts! I agree that this flag might also be just an interim solution and may produce more overhead than needed.

I'm not sure whether defaulting to `diagram-js#master` would solve the issue, since the API changes are already released there as well, which would still cause the failing tests for branches targeting `bpmn-js#master`. 

What about to simply (temporarily) skipping `wiredeps` if installing the upstream branch fails and simply using the diagram-js version which is defined in the package.json? We could revert this change afterward.

**Comment by pinussilvestrus** [comment]
I sketched this here: https://github.com/bpmn-io/bpmn-js/pull/1559/commits/f35ccdd3f8bfc19d22334d4016d6ae5cd369cbb4

**Comment by nikku** [comment]
> I'm not sure whether defaulting to diagram-js#master would solve the issue, since the API changes are already released there as well, which would still cause the failing tests for branches targeting bpmn-js#master.

The point would be to make bpmn-js master not failing anymore, i.e. release a breaking alpha release on it. In cases of urgent backports we usually create prev-major branches to do that there.

**Comment by pinussilvestrus** [comment]
We decided to follow up with an alpha release to get things in sync again. @marstamm will take it over 👍 

I'll close this one here, once we see this situation coming more often, we can decide to change things in our branching strategy.

**Pull request closed without merging**
