### PR TITLE
feat: use single arrow for connection icon

### PR DESCRIPTION
**Pull request by barmac**
image

Related to https://github.com/camunda/camunda-modeler/issues/2282

### CODE REVIEW

**Review by nikku — CHANGES_REQUESTED** [review]
To reduce the visual disturbance caused by this change I'd suggest to use a connection icon that is "in line" with other connections in the context pad:

image

**Comment by barmac** [comment]
I can do that but it will require changes in bpmn-font. 

BTW note that the default flow angle is the same as the icon I used here:

image
image

**Comment by nikku** [comment]
Asked for quick validation via with a bunch of other folks. If it is just me, let's keep it as you propose.

**Comment by barmac** [comment]
Hmm I think instead of bpmn-font changes it can be implemented in bpmn-js via icons module.

**Comment by barmac** [comment]
image

I'm not happy with this result. It looks too crispy, and even setting `shape-rendering` doesn't help.

**Comment by nikku** [comment]
@barmac We can make minor improvements to the icon to make it look more crisp:

image.

However we'll not be able to fix the issue that the new icon has a weaker visual presence then the old one. This is simply because it takes less space.

**Comment by barmac** [comment]
I experimented with text annotation:

image

**Comment by barmac** [comment]
The wrench:
image

**Comment by nikku** [comment]
@barmac Let's put up a demo where we can see this end-to-end.

**Comment by barmac** [comment]
I prepared a bpmn-font update and will post a demo link soon: https://github.com/bpmn-io/bpmn-font/pull/19

**Comment by barmac** [comment]
I've changed the PR to use the font from the linked pull request but now the icons appear broken. Not sure if this is due to some changes at fontello or I did sth wrong:

image

**Comment by nikku** [comment]
@barmac This is due to

image

**Comment by barmac** [comment]
OK so it's fontello's fault. I will adjust the PR.

**Comment by barmac** [comment]
This is how it looks like with adjustments made:

image

**Comment by marstamm** [comment]
I love how the lines match up now, rather than just being parallel to each other ❤️ 
image (2)

**Comment by nikku** [comment]
I still love the old connect icon in the way it fills a square place, but hey, let's embrace the future.

Maybe a future follow-up could be to make the connection line width the same width like the annotation line (text annotation).

**Comment by philippfromme** [comment]
I think it looks just fine.

**Comment by nikku** [comment]
@philippfromme Consider https://github.com/bpmn-io/bpmn-js/pull/1825 as an alternative. Which one works better?

| This PR | https://github.com/bpmn-io/bpmn-js/pull/1825 |
| :--- | :--- |
| image | image |

**Comment by philippfromme** [comment]
@nikku The second one works much better.

**Comment by marstamm** [comment]
+1 for #1825

**Comment by nikku** [comment]
Incorporated the final icons via https://github.com/bpmn-io/bpmn-js/pull/1822/commits/2e6b976dfa7e52285150b27f4f10fc05a315cb3c:

image

**Review by nikku — APPROVED** [review]

**Pull request merged**
