### PR TITLE
Improve layouting of boundary elements and connections on host/source/target resize

### PR DESCRIPTION
**Pull request by barmac**
New behavior: If the attachment or connections can stay in same place after resize, keep it there.

Related to https://github.com/bpmn-io/bpmn-js/issues/1289
Related to https://github.com/camunda/camunda-modeler/issues/1737
Related to https://github.com/camunda/camunda-modeler/issues/655

Requires https://github.com/bpmn-io/diagram-js/pull/452

### CODE REVIEW

**Comment by barmac** [comment]
sticky

Maybe it should be even more sticky. Notice how the event is moved when both bottom and right edge are changed. What do you think?

**Comment by barmac** [comment]
sticky-connection

Sticky connection for comparison.

**Comment by nikku** [comment]
I do not see a difference :thinking:.

**Comment by barmac** [comment]
> I do not see a difference 🤔.

Then I guess user won't see it either.

**Comment by philippfromme** [comment]
I can see the difference. And yes, it would be nice to have.

**Comment by barmac** [comment]
OK, I'll try to implement it.

**Comment by philippfromme** [comment]
@barmac Let me know when this is ready to be reviewed. 👍

**Comment by barmac** [comment]
@philippfromme @nikku Ready for review.

**Pull request merged**
