### PR TITLE
Added functionality to copy properties while replaceing element

### PR DESCRIPTION
**Pull request by korbinianHoerfurter**
This is an additional functionality for copiing all properties of an bpmn-element to another while replaceing ist (i.e. Change task type)

The code checks whether the old properties fit to the new element.

### CODE REVIEW

**Comment by pedesen** [comment]
Closed due to inactivity

**Comment by pedesen** [comment]
I reopened the ticket again, because it is a nice feature that we should implement ourselves.

**Comment by korbinianHoerfurter** [comment]
Hi,
the problem was, that the tests failed also before I added the new functionality (directly after the fork).

**Comment by nikku** [comment]
Closing this now. We will work on the functionality via #415.

**Pull request closed without merging**
