### PR TITLE
ci: fix POST_RELEASE job

### LINKED ISSUE #1979: Fix post-release job
### What should we do?

Fix post-release job which fails since automatic release was introduced. It fails to read the tag which breaks the pipeline.

Cf. https://github.com/bpmn-io/bpmn-js/actions/runs/6557498817/job/17809291824

### Why should we do it?

Our CI should work.

### PR DESCRIPTION
**Pull request by barmac**
Closes #1979

We are using release-please action outputs in this solution: https://github.com/google-github-actions/release-please-action#outputs

### CODE REVIEW

**Comment by barmac** [comment]
Manual test is running at https://github.com/bpmn-io/bpmn-js/actions/runs/6557829390

**Comment by barmac** [comment]
POST_RELEASE works. There was a problem with translations update, but I could reproduce it only when called from the POST_RELEASE action.

**Comment by barmac** [comment]
@philippfromme @marstamm ready for review.

**Review by marstamm — APPROVED** [review]
Looks like it works, great to have it fixed 🚀

**Pull request merged**
