### PR TITLE
feat(space-tool): consider lanes when resizing participant

### PR DESCRIPTION
**Pull request by philippfromme**
Related to camunda/camunda-modeler#1703

Requires https://github.com/bpmn-io/diagram-js/pull/444

### CODE REVIEW

**Comment by philippfromme** [comment]
For some reason, the `wiredeps` task succeeds in the `push` build but fails in the `PR` build. Therefore, the `PR` build fails.

**Comment by nikku** [comment]
> For some reason, the wiredeps task succeeds in the push build but fails in the PR build. Therefore, the PR build fails.

`wiredeps` does not wire PRs against `master`. @barmac can fill you in on the details, why we went that route. TLDR: if you depend on upstream changes on some feature branch what you propose is not eligible as a bug fix.

**Comment by nikku** [comment]
Not sure if I'm doing something wrong in my setup. I can, however, easily blow up the editor still:

capture cnpvQ0_optimized

**Comment by philippfromme** [comment]
I think there is still a problem with nested lanes.

**Comment by barmac** [comment]
@philippfromme are you planning to add a test case for an empty participant?

**Comment by barmac** [comment]
Also, as a fix this can be targeted at `master`, right?

**Comment by barmac** [comment]
@philippfromme and I just had a conversation. Here's a short summary:

* Philipp will publish diagram-js feature release and include it in this PR.
* The PR will be targeted at `master` as it is a fix.
* I will try to rewrite `getLanesMinHeight` so that it's easier to comprehend.

**Comment by barmac** [comment]
space

Actually, I am still able to break this. Can you please add a test case for such a situation?

**Comment by nikku** [comment]
Also, can we simply ship this as a feature, not a bug fix? As seen with the back-and-forth on this topic it's not exactly low risk.

**Comment by barmac** [comment]
> Also, can we simply ship this as a feature, not a bug fix? As seen with the back-and-forth on this topic it's not exactly low risk.

Yes, we can decide to leave it as it is.

**Comment by philippfromme** [comment]
> Actually, I am still able to break this. Can you please add a test case for such a situation?

What exactly breaks?

**Comment by barmac** [comment]
> > Actually, I am still able to break this. Can you please add a test case for such a situation?
> 
> What exactly breaks?

Sorry, there's no crash but the minimum height can be computed disregarding child element. Still, we can leave it as it is. Crash is fixed.

**Comment by philippfromme** [comment]
> disregarding child element

Are you referring to the start event? It's not a child of the lane. It's a child of the participant and is only connected to the lane through a `flowNodeRef` property of the business object. I looked into how hard it would be to consider visual children but I decided that it's outside of the scope of this issue.

**Comment by barmac** [comment]
> > disregarding child element
> 
> Are you referring to the start event? It's not a child of the lane. It's a child of the participant and is only connected to the lane through a `flowNodeRef` property of the business object. I looked into how hard it would be to consider visual children but I decided that it's outside of the scope of this issue.

All right! Let's not do anything regarding this now :)

**Comment by philippfromme** [comment]
So we can merge this as it is once @barmac is satisfied with the implementation of `getParticipantMinHeight`?

**Comment by philippfromme** [comment]
This is now ready to be merged.

**Pull request merged**
