### PR TITLE
Translate title for 'Append ReceiveTask' action

### PR DESCRIPTION
**Pull request by novrain**
This PR integrates translation module into 'Append ReceiveTask' action.

### CODE REVIEW

**Comment by oguzeroglu** [comment]
Hey,

Thanks for the PR. Could you please amend your commit message to fit our standards.

An example would be: feat(context-pad): Translate append ReceiveTask action title

**Comment by novrain** [comment]
@oguzeroglu , Thank you.
I have changed it. Is it correct?

**Comment by oguzeroglu** [comment]
Hey, no, I meant the commit message not the pull request explanation.

https://help.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message

**Comment by oguzeroglu** [comment]
I updated the commit message and the PR explanation.

**Pull request merged**
