### PR TITLE
Migrate to `babel-plugin-istanbul`

### PR DESCRIPTION
**Pull request by nikku**
The loader we use for coverage reporting is replaced by `babel-plugin-istanbul`.

This PR makes us use the later.

-----

* [x] I verified this works locally (coverage reporting)

-----

Depends on https://github.com/bpmn-io/bpmn-js/pull/1722

### CODE REVIEW

**Comment by nikku** [comment]
Ready for review. Recent commits just fix merge conflicts with `develop`.

**Comment by marstamm** [comment]
Works on my machine, but it seems like CI did not run for this one. Any chance we can maniually trigger it?

**Comment by nikku** [comment]
Seems to be an issue with the CI changes: https://github.com/bpmn-io/bpmn-js/actions/runs/2888738013

Will get these running + green.

**Comment by nikku** [comment]
I suspect it is this dude: https://github.com/bpmn-io/bpmn-js/pull/1721/commits/e9828c171609e77594d8a8f17359a06c1acbf73d

:thinking:

**Comment by marstamm** [comment]
Seens like we missed it in https://github.com/bpmn-io/bpmn-js/pull/1722

**Comment by nikku** [comment]
Yea. My bad :see_no_evil:

**Comment by nikku** [comment]
Move quick and break things!

**Comment by nikku** [comment]
Let's get this merged so CI is meaningful again :wink

**Comment by marstamm** [comment]
> Yea. My bad 🙈

I also missed it in the review 😅

**Review by marstamm — APPROVED** [review]

**Comment by nikku** [comment]
Also fixed in diagram-js (`master`): https://github.com/bpmn-io/diagram-js/commit/d259a49593b25a743fc4156cf35a59c73ec9eeae :hear_no_evil:

**Comment by nikku** [comment]
Now new Safari tests actually explode :wink

**Pull request merged**
