### PR TITLE
chore(renderer): Implemented oop paradigm for BpmnRenderer

### PR DESCRIPTION
**Pull request by felixlinker**
### Proposed Changes

* `lib/draw/BpmnRenderer.js` now has all functions implemented as prototype functions allowing for usefull inheritance

In my case, I'd like to be able to extend the `handlers`-map which wasn't possible before without making use of extensive copy'n'pasting.

### CODE REVIEW

**Comment by nikku** [comment]
I'd like to understand a little bit more about your case:

* Why would you like to extend the handler map?
* How do you plan to extend it?

**Comment by felixlinker** [comment]
Sorry, I was a bit wrong in my op. I don't want to extend the `handlers`-map but the `PathMap`! I'd like to do something like this:

```js
MyRenderer.prototype.drawShape = function(parentGfx, element) {

  if (is(element, 'bpmn:Task') && shouldHaveCustomIcon(element)) {
    var task = this.handlers['bpmn:Task'](parentGfx, element);

    var pathData = this.pathMap.getScaledPath('CUSTOM_ICON', { /* ... */ });
    this.drawPath(parentGfx, pathData, { /* ... */ });

    return task;
  } else {
      return BpmnRenderer.prototype.drawShape.call(this, parentGfx, element);
  }
};
```

Without my commit, I'd be unable to call functions like `drawPath` as they're hidden in the constructor by closure.

**Comment by nikku** [comment]
Thanks for clarifying. 

In general, as part of this library we distinguish between private (`_` prefixed) and public members of services. From what it looks like the stuff you're doing is more like _you better know what you're doing_. That said, all methods you expose should be private. Same goes for the member properties (i.e. _pathMap_ and friends). 

If it is just about changing the element decoration (the icon in this case), why not create an extension point that allows you to just hook into the decoration phase?

Example: 

```javascript
MyRenderer.prototype.decorateTask = function(parentGfx, element) {

  if (is(element, 'bpmn:Task') && shouldHaveCustomIcon(element)) {
    var pathData = pathMap.getScaledPath('CUSTOM_ICON', { /* ... */ });
    return this.drawPath(parentGfx, pathData, { /* ... */ });
  }
  
  return BpmnRenderer.prototype.decorateTask.call(this, parentGfx, element);
};
```

This is a narrowed down extension point that serves one well defined purpose. Plus, it would be easy to test that extension point, too.

**Comment by felixlinker** [comment]
I currently don't see this working other than when accompanied by a new `decoratorHandlerMap`. One could than extend `BpmnRenderer.prototype.drawShape` like this:
```js

**Comment by nikku** [comment]
All right then.

My suggestion would be: 

* expose the minimal subset of functions you need with the renderer:

    ```javascript
    function Renderer(...) {

      ... // existing render code

      // internal API, exposed for extensions
      this._drawPath = drawPath;
      this._foo = foo;
      this._bar = bar;
    }
    ```

    Mind the usage of `_` to denote these are actually internal APIs that may break any time.

* if you want us to recognize that we break access to these internals, add test cases for them 😉 .

**Comment by felixlinker** [comment]
So that means you'd be ok with a PR that simply adds the following LOC?
```js
function BpmnRenderer(...) {
  /* ... */
  this._drawPath = drawPath;
}
```

**Comment by nikku** [comment]
Yes. Plus think about, whether to add test cases or not.

**Pull request closed without merging**
