### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by szurilo**
__Which issue does this PR address?_

Closes #

Project structure is not okay without this change.

### CODE REVIEW

**Comment by nikku** [comment]
You're on Windows, right? That should explain why the setup instructions don't work for you.

In a *nix like environment `(cd foo && bar)` has the semantics 

* move to `foo`
* execute `bar`
* go back

**Comment by szurilo** [comment]
Are you sure? I just tried it on CentOS and with these commands the CWD is /foo
cd /
mkdir foo
cd foo && touch bar

**Comment by nikku** [comment]
You must execute the statement as shown above, on a single line: `(cd foo && bar)`.

**Comment by nikku** [comment]
The brackets matter.

**Comment by szurilo** [comment]
Ahh, you are right, thanks for the clarification. I assumed the brackets are there for commenting only :)

**Pull request closed without merging**
