### PR TITLE
Feature - handling multiple diagrams in bpmn file

### PR DESCRIPTION
**Pull request by Ichigo85**
This branch provides multiple diagram functionalities to bpmn-js.

With the new feature, I provided also a simple test case.

This code was originally copied from chor-js project, copyright 2018, under the MIT license.

### CODE REVIEW

**Comment by nikku** [comment]
Could you showcase via a screenshot what you implemented? A rationale why you'd like to see it in the core would help, too.

In some thread we discussed that we do probably _not_ want it in the core.

**Comment by nikku** [comment]
Related to [this forum thread](https://forum.bpmn.io/t/how-to-add-multidiagram-functionality-on-bpmn/3840/5)

**Comment by Ichigo85** [comment]
[Here](https://github.com/sharedchains/bpmn-js-modeler-demo) is an example of modeler demo which implements a small panel for this feature, as shown in the image below.
image

After you answered in the forum thread, I modified our project to keep in core only the command handlers, and I made the modeler example linked above with switching controls.

**Comment by Ichigo85** [comment]
Hi @nikku , any news on this pull request? Is there something I can do to help you?

**Comment by nikku** [comment]
Sorry for keeping that PR hanging forever. I simply forgot about it. 

As it looks like this functionality is wonderfully self-contained, however it seems to be taken from another place and used under a separate license (cf. https://github.com/bpmn-io/bpmn-js/pull/1184/files#diff-667d38a82a1b5afa3003d202177694ddbc070cbab9ca6bddfe4c4165c0ddf945). As a result we cannot simply include it in our code base. Rather, I encourage you to extract that functionality into a bpmn-js extension, i.e. `bpmn-js-multi-diagram` and file a PR against our [awesome list](https://github.com/bpmn-io/awesome-bpmn-io#bpmn-js) to with the link to get people to know it. 

It is a great contribution, after all.

**Pull request closed without merging**
