### PR TITLE
[WIP] chore(project): upgrade lodash to min-dash

### PR DESCRIPTION
**Pull request by TheSharpieOne**
Fixes https://github.com/bpmn-io/diagram-js/issues/234

### Proposed Changes

* Switch out lodash for min-dash
* Add some utils for functions which lodash had and min-dash will not provide (fill the gap)

### CODE REVIEW

**Comment by nikku** [comment]
Do you plan to follow up on this PR?

**Comment by TheSharpieOne** [comment]
Yes. I didn't have time the last couple of days, but I should have some be able to finish it up today.

**Comment by nikku** [comment]
Thanks for letting us know.

**Comment by nikku** [comment]
You may now (and should!) use the utilities `size`, `flatten`, `has` and `merge` from min-dash.

For object-based pattern matching, please use the `matchPattern(obj)` utility:

```javascript
var results = find(collection, matchPattern({ id: '1' }));
```

**Comment by nikku** [comment]
Merged your changes with additional adjustments via https://github.com/bpmn-io/bpmn-js/pull/773.

Thanks!

**Pull request closed without merging**
