### PR TITLE
 Vertically Auto-Place Elements

### LINKED ISSUE #2110: Vertically Auto-Place Elements
### Is your feature request related to a problem? Please describe.

Problem: Elements in vertical pools and lanes are auto-placed horizontally.

### Describe the solution you'd like

Auto-place elements within vertical containers vertically from top to bottom. Make Sequence and Message Flows match this direction.

In a more abstract way: The result model should look like a horizontally modeled process that was mirrored on the model axis from top-left to bottom-right.

sample-auto-place

### Describe alternatives you've considered

Not implementing this feature. But I think it's worth now that layouting vertical containers is possible.

At the moment I don't see a way to make this work in general, i.e. for models without vertical pools. So I would limit this feature to the insides of vertical pools.

### Additional context

Related to #507

I would like to make a contribution.

### PR DESCRIPTION
**Pull request by sombrek**
Closes #2110

This implements auto place and flow layouting for vertical pools and lanes and works only within those containers.

It's an almost exact mapping of the horizontal layout.
The exception: Per #2110, data objects are placed to the left of tasks and text annotations are placed to their right (only for vertical layouts).

Since data objects are not avilable by default, you can use this Context Pad code for testing (insert near `append.append-task`):

```
        'append.data-store': appendAction(
          'bpmn:DataStoreReference',
          'bpmn-icon-data-store',
          'Data Store TEST'
        ),
        'append.data-object': appendAction(
          'bpmn:DataObjectReference',
          'bpmn-icon-data-object',
          'Data Object TEST'
        ),
```

The initial dimensions and content of sub processes are still laid out horizontally.
I think that's a feature for the future. At the moment I'm not sure how much I can do about that.

### CODE REVIEW

**Comment by sombrek** [comment]
@barmac Just remembered to notify you :-)

**Comment by barmac** [comment]
Hey, I was busy last week but will look into this soon.

**Comment by barmac** [comment]
Unfortunately, we are super busy this week, but I will for sure review this beginning next week.

**Comment by barmac** [comment]
I am looking into this right now. Once again sorry for the delay.

**Comment by barmac** [comment]
I tried this out together with create-append-anything and I like the interaction.

https://github.com/bpmn-io/bpmn-js/assets/28307541/fc844d4e-a206-49e7-804a-cbd614f3cc12

**Comment by barmac** [comment]
Thank you for your contribution!

**Comment by Drckk** [comment]
Looking forward to this release! 👍

**Comment by barmac** [comment]
Not sure why this has not been released yet. I will make sure it's done.

**Comment by barmac** [comment]
Released via v17.3.0: https://github.com/bpmn-io/bpmn-js/pull/2141

**Pull request merged**
