### PR TITLE
fix: label text visible while editing

### PR DESCRIPTION
**Pull request by abdul99ahad**
### Proposed Changes

 
The Bug
camunda-lane-label_bug

Resolution 
Aug-27-2024 16-52-49

Related to: [#4477](https://github.com/camunda/camunda-modeler/issues/4477)
### Checklist

To ensure you provided everything we need to look at your PR:

* [x] **Brief textual description** of the changes present
* [x] **Visual demo** attached
* [ ] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Review by nikku — CHANGES_REQUESTED** [review]
We don't usually show borders anymore, so I wonder if/why the border is necessary in this case?

I also wonder if this is the appropriate fix. Why does it "just work" for participants, and extra configuration is needed for lanes?

Let's adjust the reference to the linked issue in commit and PR [as discussed](https://camunda.slack.com/archives/GP70M0J6M/p1724829095130249).

**Comment by abdul99ahad** [comment]
> We don't usually show borders anymore, so I wonder if/why the border is necessary in this case?

The GIF mentioned in issue under expected behavior has borders in it, so I assumed it will have borders.

> I also wonder if this is the appropriate fix. Why does it "just work" for participants, and extra configuration is needed for lanes?

It works for other elements and participants as their different configurations are set in the same file. 

> Let's adjust the reference to the linked issue in commit and PR [as discussed](https://camunda.slack.com/archives/GP70M0J6M/p1724829095130249).

I have adjusted the commit and PR by mentioning the related issue i.e., camunda-modeler: #4477

**Comment by nikku** [comment]
> It works for other elements and participants as their different configurations are set in the same file.

I'm sorry, but that is not correct. The label background is not set to white for, i.e. participants. Instead a `djs-label-hidden` class is added, hiding the label for the time of editing. I believe we should adapt the same mechanism for lanes, if possible.

Cf. capture that demonstrates the participant behavior:

screenshot LkG79J

**Comment by abdul99ahad** [comment]
> > It works for other elements and participants as their different configurations are set in the same file.
> 
> I'm sorry, but that is not correct. The label background is not set to white for, i.e. participants. Instead a `djs-label-hidden` class is added, hiding the label for the time of editing. I believe we should adapt the same mechanism for lanes, if possible.
> 
> Cf. capture that demonstrates the participant behavior:
> 
> capture CNy2WF_optimized [ capture CNy2WF_optimized ](https://private-user-images.githubusercontent.com/58601/362247500-2e17ad6d-b753-48f7-ac91-69f74521efa2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDMyNzAsIm5iZiI6MTcyNDg0Mjk3MCwicGF0aCI6Ii81ODYwMS8zNjIyNDc1MDAtMmUxN2FkNmQtYjc1My00OGY3LWFjOTEtNjlmNzQ1MjFlZmEyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDExMDI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MzdmZWUyOTBkODMyYzY0N2E1MjIxNTlkNWU0NDlkMTE3YWExNmJhMzNmNGYxNTc4YmY0NGFkOTc2ZDBhMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2Eln_1YCnwHkL5l1Miqs_USzYcLwb93p-kbOHOLjSuI) [ ](https://private-user-images.githubusercontent.com/58601/362247500-2e17ad6d-b753-48f7-ac91-69f74521efa2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDMyNzAsIm5iZiI6MTcyNDg0Mjk3MCwicGF0aCI6Ii81ODYwMS8zNjIyNDc1MDAtMmUxN2FkNmQtYjc1My00OGY3LWFjOTEtNjlmNzQ1MjFlZmEyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDExMDI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MzdmZWUyOTBkODMyYzY0N2E1MjIxNTlkNWU0NDlkMTE3YWExNmJhMzNmNGYxNTc4YmY0NGFkOTc2ZDBhMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2Eln_1YCnwHkL5l1Miqs_USzYcLwb93p-kbOHOLjSuI)

I'm sorry for the confusion with my previous explanation—I got mixed up with the terminology. I was actually comparing it with the implementation for Event labels, but you're right about how it works differently for participants and other elements. I've updated the fix to align with the mechanism you mentioned. Thank you for pointing this out; your insight is very helpful as always. ✨

**Comment by nikku** [comment]
I linked the related issue in the commit via 

```
Related to https://github.com/camunda/camunda-modeler/issues/4477
```

**Pull request merged**
