### PR TITLE
fixed ContextPadProvider types

### PR DESCRIPTION
**Pull request by J4CKVVH173**
### Proposed Changes

Fix the [issue](https://github.com/bpmn-io/bpmn-js/issues/2203). Added type to the function's constructor.

Related to {https://github.com/bpmn-io/bpmn-js/issues/2203}

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] **Brief textual description** of the changes present
* [] **Visual demo** attached
* [] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by barmac** [comment]
Thanks! Could you also provide a type test to this contribution? Look at this file as an example: https://github.com/bpmn-io/bpmn-js/blob/main/lib/BaseModeler.spec.ts

**Comment by J4CKVVH173** [comment]
I didn't get the idea. I need to create an instance of ContextPadProvider  and then what?

**Comment by barmac** [comment]
This code is not run, we just want to verify that the typescript compiler passes.

**Review by nikku — APPROVED** [review]
Thanks!

**Comment by nikku** [comment]
@barmac I decided to merge this one; as this is not about external API improvement, but internal typing I'm afraid there is not much we can simply test here.

**Pull request merged**
