### PR TITLE
fix(moddle): Add additional default moddle descriptor(s) to viewer

### PR DESCRIPTION
**Pull request by davcs86**
This PR allows adding default moddle descriptor(s) for custom bower bundles.

Works similar to adding default modules described [here](https://github.com/bpmn-io/bpmn-js-examples/blob/master/custom-bower-bundle/README.md)

**Example:**

```js
// load additional moddle descriptors
var additionalModdleDescriptors = {
  'camunda': require('camunda-bpmn-moddle/resources/camunda'),
  'your-custom-descriptor': require('./your-descriptor/descriptor-definition') // your .json file
};

// add additional (default!) moddle descriptors to viewer
BpmnViewer.prototype._moddleExtensions = additionalModdleDescriptors;
```

### CODE REVIEW

**Comment by vladimirskatusenoks** [comment]
Thank you, all looks good. Please add a test similar to [`this`](https://github.com/bpmn-io/bpmn-js/blob/master/test/spec/ViewerSpec.js#L508) and will be happy to merge.

**Comment by davcs86** [comment]
Hi, I just added a very basic example. Let me know if you need something more complex.

**Comment by vladimirskatusenoks** [comment]
Hi, couple of points:
- please make sure there is no `.only` on any of the tests
- squash all commits into one (e.g. 'feat(moddle): add additional (default!) moddle descriptor to viewer')
- rewrite the test to actually use new functionality like so:
```
      var xml = require('../fixtures/bpmn/extension/custom.bpmn');

      var additionalModdleDescriptors = {
        custom: require('../fixtures/json/model/custom')
      };

      Viewer.prototype._moddleExtensions = additionalModdleDescriptors;

      // given
      viewer = new Viewer({
        container: container,
        moddleExtensions: {
          camunda: camundaPackage
        }
      });
```

**Comment by davcs86** [comment]
Hi,

- Remove `.only`, [done](https://github.com/davcs86/bpmn-js/commit/f557d1c8df459aa8c5ec76eecda02bd0cfa4351d#diff-e2dfad16bb9fc5150447e81bb05c3c2cR676)
- I _squashed_ the commits but I couldn't rename.
- Rewrite test, [done](https://github.com/davcs86/bpmn-js/commit/f557d1c8df459aa8c5ec76eecda02bd0cfa4351d#diff-e2dfad16bb9fc5150447e81bb05c3c2cR547)

**Comment by vladimirskatusenoks** [comment]
Thank you for the PR.

I have rebased the changes, updated some formatting and merged into `master` branch.

**Pull request closed without merging**
