### PR TITLE
Attempt to fix issue #1462 - StartEvent (non interrupting) is replaced with the plain StartEvent when element is placed on the diagram

### PR DESCRIPTION
**Pull request by 0x00000001A**
Attempt to fix issue #1462 - StartEvent (non interrupting) is replaced with the plain StartEvent when element is placed on the diagram.

Tests (BpmnReplacePreviewSpec) are need to be fixed and/or new tests should be added.
@barmac I'll glad if you can help with test cases.

### CODE REVIEW

**Comment by barmac** [comment]
Hi,

Thanks for creating this PR. Indeed some tests in the replace preview started to fail. I'll have a look at this and perhaps the issue can be fixed.

**Comment by barmac** [comment]
OK so I can see that the problem is not within the `BpmnReplacePreview` but rather in the pull request itself. The tests fail with a reason -> If you drag a non-interrupting timer start event from an event subprocess, the preview is not updated correctly. The behavior is caused strictly by the changes in `BpmnRules#canReplace`.

Please feel free to adjust the PR to fix the issue detected by the test.

**Comment by 0x00000001A** [comment]
@barmac 
I've double checked everything, and here what I got:
You're right, that the problem is [this pull request](https://github.com/bpmn-io/bpmn-js/pull/1434). I've tried to understand the problem that the specified PR resolves and I've ended up with the following suggestion: if this PR (that mentioned before) is about disallowing copy-paste some types of start events to the subtasks, would not be better to check if the target has "bpmn:SubTask" type?

I've just tried to add this condition (target type checking) and everything is ok, tests are passing and copy-paste typed start event is blocked as it should (according to the PR).

Actually, I've changed just one line (ReplaceElementBehaviour, line 32):
```js
var canReplace = is(target, 'bpmn:SubProcess') && bpmnRules.canReplace(elements, target);
```

What do you think about it?

**Comment by barmac** [comment]
Hey, I had a look at the new solution you prepared. It turns off the ReplaceElementBehavior whenever the target is not a subprocess. This, however, makes it possible to copy a non-interrupting event to a process which is not allowed by the spec. I'd suggest to look for the solution within the rules code as it is the place where the tool decides to that the event should be replaced.

**Comment by barmac** [comment]
For comparison, I created a test case which is added via https://github.com/bpmn-io/bpmn-js/pull/1469

**Comment by barmac** [comment]
I am closing this for now but we can reopen the PR once you want to implement it.

**Pull request closed without merging**
