### PR TITLE
fix(label-editing): cancel on element deletion

### PR DESCRIPTION
**Pull request by nikku**
Closes https://github.com/bpmn-io/bpmn-js/issues/1664

### CODE REVIEW

**Comment by nikku** [comment]
Builds (optionally) on top of https://github.com/bpmn-io/diagram-js-direct-editing/pull/25.

**Comment by philippfromme** [comment]
Should we update the `diagram-js-direct-editing` dependency as well?

**Comment by nikku** [comment]
> https://github.com/bpmn-io/bpmn-js/pull/1666#issuecomment-1136780612

Done. I've done it elsewhere, too. But I guess it does not hurt to do it close to where it is needed.

**Review by barmac — COMMENTED** [review]
I cannot reproduce the issue as context pad closes as soon as I start direct editing. I think it would make sense to add a test case for a situation when not the element, but just the label gets removed.

**Comment by barmac** [comment]
OK, I had to append element first as @nikku guided me. In the PR, I cannot reproduce the issue anymore.

**Review by barmac — APPROVED** [review]

**Pull request merged**
