### PR TITLE
feat(modeling): add isHorizontal=true to participant/lane shapes

### LINKED ISSUE #934: Add isHorizontal=true to Participant / Lane DI shapes
__Is your feature request related to a problem? Please describe.__

The `isHorizontal` attribute on participant and lane DI shapes is meta-data that helps editors to understand how these elements are laid out. Quoting from the BPMN spec (p. 373): 

> + isHorizontal : Boolean [0..1]
> an optional attribute that should be used only for Pools and Lanes. It determines if it should be depicted horizontally (true) or vertically (false).

The attribute is not necessarily required, thus this feature request falls into the forgiveness / compatibility category.

__Describe the solution you'd like__

We should add the attributes, as we only support horizontal modeling anyway and "fix" existing diagrams by gradually introducing the 

* [ ] add `isHorizontal=true` on newly created participant / lane DI shapes
* [ ] add `isHorizontal=true` on update participant / lane DI shapes

__Describe alternatives you've considered__

* ignore compatibility concerns and keep things as is

__Additional context__

Reported in https://github.com/camunda/camunda-modeler/issues/1096, too.

### PR DESCRIPTION
**Pull request by barmac**
Closes #934

### CODE REVIEW

**Comment by philippfromme** [comment]
> Hint: We have to set the `isHorizontal` property on the `BPMNShape` element of the participant in the DI. Therefore, we need extend the [model](https://github.com/bpmn-io/bpmn-moddle/blob/master/resources/bpmn/json/di.json).

**Comment by nikku** [comment]
We don't need to extend the model, it is all there as part of `bpmndi`: https://github.com/bpmn-io/bpmn-moddle/blob/master/resources/bpmn/json/bpmndi.json#L49. We just have to update the DI in the appropriate place.

I'll discuss the solution with @barmac next week.

**Comment by barmac** [comment]
Let's do this. Temporarily, I renamed the issue so that it's clear we're going to change it next week.

**Comment by nikku** [comment]
Looking good from the user perspective. 

Could you update the PR to use the same update mechanism we use [in the `BpmnUpdater`](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/modeling/BpmnUpdater.js#L141).

**Comment by barmac** [comment]
Updated to trigger change only on shape creation, resizement and movement. It remains irreversible.

**Pull request merged**
