### PR TITLE
Handle Adding Vertical Lanes

### LINKED ISSUE #2086: Handle Adding Vertical Lanes
### Is your feature request related to a problem? Please describe.

Adding vertical lanes to existing pools should be supported. Currently, new lanes are placed as if they were added to a horizontal pool, i.e.
- they leave space for the label on the left side of the pool
- they split vertical pools vertically
- they set `isHorizontal=true`

<details>
  <summary>Adding Issue Demonstration</summary>

add-lane-vertical

</details>

### Describe the solution you'd like

Implement adding vertical lanes to existing pools and lanes by supporting that feature under the hood.
I think this can be done unintrusively without UI changes, by ensuring that lanes are always added horizontally/vertically according to their parent pool. The downside is that the icons will not match the actual action.

Splitting lanes will be implemented separately.

### Describe alternatives you've considered

Vertical variants of the "add lane" buttons could be introduced, but that would give the feature more exposure (i.e. less _under the hood_-ness as required by #507).

### Additional context

This is related to #507 and I would like to contribute the implementation.

### PR DESCRIPTION
**Pull request by sombrek**
Closes #2086

- I fixed come CRLF line endings in a separate commit.
- I did not add tests for undefined lanes, since special handling for such lanes already exists and is tested (`IsHorizontalFixSpec`).

### CODE REVIEW

**Comment by nikku** [comment]
As we're adding more features in the context of vertical lanes: I think it makes sense to add to dedicated "vertical" examples to our [modeler](https://github.com/bpmn-io/bpmn-js/blob/develop/test/spec/ModelerSpec.js) and [viewer](https://github.com/bpmn-io/bpmn-js/blob/develop/test/spec/ViewerSpec.js) specs. These are the ones we usually use for end-to-end (integration) testing.

**Comment by barmac** [comment]
Thank you for your contribution.

I've added a vertical collaboration example via https://github.com/bpmn-io/bpmn-js/pull/2090/commits/1cf81d2375ce67c2955702ff549f4297c7dc8b30

image

In this PR, the nested lane is still not handled correctly:

https://github.com/bpmn-io/bpmn-js/assets/28307541/1bb253ce-ccc8-47ed-a161-a84b91ebfbc1

We may consider to flip the icons in the future, but it's not required to merge this.

**Comment by barmac** [comment]
As a follow-up, I created an issue for the hit box: https://github.com/bpmn-io/bpmn-js/issues/2093

**Comment by sombrek** [comment]
@barmac Thanks for the additional test and the follow-up.

> In this PR, the nested lane is still not handled correctly:

Honestly, until now I didn't think of splitting lanes as adding nested ones, so I didn't work on splitting yet. But I see your point now. Would you like me to include splitting in this PR (may take two weeks) or can I do it in a separate one?

**Comment by barmac** [comment]
It's OK to have it as a separate PR then. I will merge this.

**Comment by barmac** [comment]
I checked the issue again. You mentioned splitting there: https://github.com/bpmn-io/bpmn-js/issues/2086#issue-2094227764 So I won't close it but rather keep a link in this PR.

**Comment by barmac** [comment]
Released via https://github.com/bpmn-io/bpmn-js/pull/2094

**Pull request merged**
