### PR TITLE
fix: updates spelling mistakes - mostly just in comments

### PR DESCRIPTION
**Pull request by jonoirwinrsa**
_Which issue does this PR address?_

No issue open for it.

Closes #

Fixes some spelling mistakes - mostly in comments but once in a function name (only used in that module).

### CODE REVIEW

**Comment by nikku** [comment]
Thanks for your PR.

Could you separate the documentation changes from the context pad change? 

That helps us to handle these separately.

**Comment by jonoirwinrsa** [comment]
Yeah sure 👌

**Comment by pinussilvestrus** [comment]
Hi @jonoirwinrsa,

can you squash and reword your commit to fit our [contribution guidelines](https://github.com/bpmn-io/bpmn-js/blob/develop/.github/CONTRIBUTING.md#creating-a-pull-request)? So we have one clear commit for all changes, something like

```sh
chore(project): correct spelling mistakes
```

same with your second PR https://github.com/bpmn-io/bpmn-js/pull/1187

**Comment by nikku** [comment]
Squashed and merged, thanks :tada:.

**Pull request merged**
