### PR TITLE
Reposition label to free space

### LINKED ISSUE #738: Reposition gateway labels to wherever free space is
Users would like to change the default gateway label position to be [always on top](https://forum.camunda.org/t/labels-on-gateways-should-default-to-above/3302/7).

I'd rather adjust label positions to automatically move to the free space around the gateway: 

foo

### PR DESCRIPTION
**Pull request by nikku**
__Demo__

foo

Closes #738

### CODE REVIEW

**Comment by philippfromme** [comment]
One case that is missing is moving elements:

foobar

I feel like reconnecting and moving the element should have the same effect on the label position.

**Comment by nikku** [comment]
Good catch. Will update the PR accordingly.

**Comment by nikku** [comment]
This also seems to break label adjustment 〽️ 🎉.

**Comment by philippfromme** [comment]
Ooops. 😨

**Comment by nikku** [comment]
Reacting on `connection.layout` now, too via https://github.com/bpmn-io/bpmn-js/pull/739/commits/8fbf252e79ccd5239c78006869a822d9b46d7a13.

**Comment by nikku** [comment]
The bug I was mentioning was that external labels would move twice, once via `LabelSupport` and once via the `AdaptiveLabelPositioningBehavior`.

I've addressed this issue in https://github.com/bpmn-io/diagram-js/pull/238/commits/87468a7cf9d9146db248382856b7b5a378c6839c (to be merged into diagram-js via PR https://github.com/bpmn-io/diagram-js/pull/238).

**Comment by nikku** [comment]
Can be reviewed again.

**Pull request closed without merging**
