### PR TITLE
Minor Changes.

### PR DESCRIPTION
**Pull request by BreathlessVictor**
Changed a sentence and minor grammar or semantic changes done.

__Which issue does this PR address?__

Closes #

__Acceptance Criteria__

* [ ] Corresponds to the concept 
* [x] Corresponds to the design 

__Definition of Done__

* [ ] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [ ] corresponds to [the code standards](https://github.com/bpmn-io/bpmn-js/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [ ] passes Continuous Integration checks
* [ ] available as feature branch on GitHub
  * [ ] contains the cleaned up commit history
  * [ ] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [ ] a single commit closes the issue via Closes #issuenr

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Please explain how those changes are improvements to the existing code base.

**Comment by BreathlessVictor** [comment]
Hi, when I went through the document, I observed that the link for the prepackaged library could be placed earlier than the library in order to give it a Wikipedia- style look, where the hyperlink comes before the rest of the statement. I also made the statement grammatically correct by doing the necessary changes. Also assigning the word 'best' before any words works to attract people towards the point in focus.
Thanks.

**Comment by BreathlessVictor** [comment]
Any changes, sir?

**Comment by pinussilvestrus** [comment]
You can identify missing work by scamming our definition of done. E.g., the commit message does not fit our guidelines. Also, I'm still not sure, whether any of your proposed changes are real improvements.

**Comment by BreathlessVictor** [comment]
I understand your confusion. The suggests I have given are in fact, improvement over the previous version. As  I said , in Wikipedia we see that to link a new topic to the current topic they embed they hyperlink in the statement, example in the attached image.(notice how they are linking the new topic before actually reaching the topic in discussion). This is what I tried to achieve here. Also, we know how psychology plays an important part in people's choice and decisions. So I tried to use the psychological effect by adding the word 'best' before the first statement.
I hope this clears your doubts.
Thanks
2020-10-01_LI

**Comment by philippfromme** [comment]
We do not accept PRs that do not substantially improve our toolkit. For potential improvements have check out at the [open issues](https://github.com/bpmn-io/bpmn-js/issues) of this repository.

I hope this clears your doubts.
Thanks

**Pull request closed without merging**
