### PR TITLE
chore(draw): expose extension points

### PR DESCRIPTION
**Pull request by nikku**
+ clearly documented as *UNSAFE*
+ add test cases
+ tested existing *UNSAFE* handler endpoint

### CODE REVIEW

**Comment by marstamm** [comment]
Could you give a little context on the use-case? I guess it is to get access to the render functions outside of the `BpmnRender`, correct?

**Comment by nikku** [comment]
Exactly. The use-case is that I am plugging in my own renderer to do some work, but delegate to the `bpmnRenderer` for the heavy lifting.

I.e. I want to render a task but add my special icon to it.

**Review by marstamm — APPROVED** [review]
:rocket:

**Comment by nikku** [comment]
The way to do this is to check internal state (cf. https://github.com/bpmn-io/connectors-modeling-demo/blob/master/connectors-extension/ConnectorTaskRenderer.js#L56).

By having an indirection this becomes easier to handle.

**Pull request merged**
