### PR TITLE
fix context pad positioning when the container has a left offset

### PR DESCRIPTION
**Pull request by mhariri**

### CODE REVIEW

**Comment by mhariri** [comment]
#270 now with a unit test

**Comment by ricardomatias** [comment]
I've merged this and refactored your test case as not to use the TestContainer's css, because it was slowing down the whole test suite. You can see the changes I made in this  [commit](https://github.com/bpmn-io/bpmn-js/commit/437a28b95361d45f42113c461a9293f87a7bec429).

**Comment by mhariri** [comment]
yes, that's much cleaner! Good job!

**Comment by mhariri** [comment]
Ricardo, When will this fix go into a release? When is the next release?

**Comment by ricardomatias** [comment]
@mhariri, we don't have release dates. But you can follow our [Milestone](https://github.com/bpmn-io/bpmn-js/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22012+-+Boundary+Events%22) progress, which indicates what issues we're tackling for the next release.

**Comment by mhariri** [comment]
This project is awesome, the only thing I could wish for is monthly releases. Anyway, keep up the good work!

**Pull request closed without merging**
