### PR TITLE
Improve navigation inside large participants

### PR DESCRIPTION
**Pull request by barmac**
Related https://github.com/camunda/camunda-modeler/issues/238

Requires https://github.com/bpmn-io/diagram-js/pull/371

Closes https://github.com/bpmn-io/bpmn-js/issues/957

### CODE REVIEW

**Comment by nikku** [comment]
Does this cover sub-processes, too? We must include these, as they can be huge container elements, too.

**Comment by barmac** [comment]
No, I will cover this then.

**Comment by barmac** [comment]
So I tried the easy way and ended up with an infinite loop 😆 
loop

**Comment by barmac** [comment]
Note for myself: I discovered that at some point SubProcess becomes a child of itself. Then, the recursive search destroys everything.

**Comment by barmac** [comment]
Just pushed a working demo. It needs dynamic tests too, though. Notice change in diagram-js which occured to be required for the progress.

**Comment by barmac** [comment]
This requires more work as we currently treat equally expanded and collapsed elements which should not take place.

**Comment by barmac** [comment]
However, the ugly indefinite loops bugs are already resolved with recent commits :)

**Comment by barmac** [comment]
@nikku I added collapsed shape support so this is ready for review.

**Comment by barmac** [comment]
Apparently this seems to close https://github.com/bpmn-io/bpmn-js/issues/957

**Comment by nikku** [comment]
> Apparently this seems to close #957

Apparently :wink:

**Pull request merged**
