### PR TITLE
Resize vertical lanes

### LINKED ISSUE #2062: Resizing Vertical Pools and Lanes
### Is your feature request related to a problem? Please describe.

Resizing vertical pools and lanes should be supported. Currently, there are several problems when trying to resize:
- lanes may "jump" as they use the minimum dimensions of horizontal pools
- resizing a pool "from the head" causes lanes to overlap the pool label
- resizing lanes horizontally incorrectly adjust widths of neighboring lanes
- the space tool doesn't allow vertical black-box pools to be resized vertically

<details>
  <summary>Resize Issue Demonstration</summary>

pool-issues-resize

</details>

### Describe the solution you'd like

- resizing of the pools and lanes works as expected
  - minimum dimensions are set appropriately
  - space tool resizes vertical pools and lanes appropriately

### Describe alternatives you've considered

Do not support resizing vertical pools and lanes.

### Additional context

This is related to #507 and I would like to contribute the implementation.

### PR DESCRIPTION
**Pull request by sombrek**
Closes #2062

This makes resizing by handles and space tool work for vertical pools and lanes.

I just saw that ResizeBehavior.js, SpaceToolBehavior.js and their Spec files have Windows line endings that my IDE didn't make me aware of. They now have Unix-style line endings. Is that acceptable for you?

### CODE REVIEW

**Comment by barmac** [comment]
I'm sorry, I didn't manage to have a thorough review of this, but will have a look next week.

**Comment by sombrek** [comment]
@barmac Don't worry. Thanks for the time you invest in the review.

I used the chance to make an adjustment.
There was one instance where I confused participant and lane in SpaceToolBehavior, I fixed that. The behavior remains the same.
I also added a small set of tests to cover more of my code.

Unfortunately, I created multiple commits. Please provide some squashing support when checking that in.

**Review by barmac — COMMENTED** [review]
Once again sorry for the delay. The interaction is mostly good, but there is a difference in the minimal height when shrinking happens from the bottom and from the top:

https://github.com/bpmn-io/bpmn-js/assets/28307541/7900d28a-ce4a-48c1-8354-dbb3b6dbdc93

**Comment by barmac** [comment]
BTW I've found an edge case which can be reproduced with horizontal participants as well. There is no need to fix this in this PR though. I wouldn't really bother creating an issue for this, too:

https://github.com/bpmn-io/bpmn-js/assets/28307541/f9dc4d9d-4f3a-4f37-a3f0-bcb43cd6a567

**Review by barmac — COMMENTED** [review]
A challenge to solve in the future:

https://github.com/bpmn-io/bpmn-js/assets/28307541/21ddc9a0-3c0a-450f-a306-76d85fcc14dd

**Comment by barmac** [comment]
> Once again sorry for the delay. The interaction is mostly good, but there is a difference in the minimal height when shrinking happens from the bottom and from the top:
> 
>  Screen.Recording.2024-01-19.at.16.50.16.mov

This problem can be noticed only if the participant contains child lanes.

**Comment by sombrek** [comment]
@barmac Thank you very much for your thorough review. Glad you were able to make it.

> Once again sorry for the delay. The interaction is mostly good, but there is a difference in the minimal height when shrinking happens from the bottom and from the top:

I can reproduce this also for horizontal pools. I'd be happy if we could treat this as a pre-existing bug and not as a failure in the PR, just like the second issue you discovered.

> A challenge to solve in the future:

This is actually on my list already, but out of scope for this PR. I plan to fix add/delete/split separately.

**Comment by barmac** [comment]
> I can reproduce this also for horizontal pools. I'd be happy if we could treat this as a pre-existing bug and not as a failure in the PR, just like the second issue you discovered.

I was able to reproduce it for horizontal lanes too. Let's keep as is it then.

**Pull request merged**
