### PR TITLE
feat(replace-menu): update label of collapsed pool

### PR DESCRIPTION
**Pull request by pinussilvestrus**
__Which issue does this PR address?__

* Indicate the action in a clearer, more standard-compliant way --> replaces an expanded pool with an empty "black box" + removing its content.
* We will not update the action identifier (`replace-with-collapsed-pool`) to avoid breaking changes.
* Make it possible to retrieve label via function

Related to camunda/camunda-modeler#2022

__Acceptance Criteria__

* [ ] Corresponds to the concept 
* [ ] Corresponds to the design 

__Definition of Done__

* [ ] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [ ] corresponds to [the code standards](https://github.com/bpmn-io/bpmn-js/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [ ] passes Continuous Integration checks
* [ ] available as feature branch on GitHub
  * [ ] contains the cleaned up commit history
  * [ ] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [ ] a single commit closes the issue via Closes #issuenr

### CODE REVIEW

**Comment by barmac** [comment]
What about the "Expanded Pool"? Do we want to keep it that way or maybe come up with something which aligns better with "Empty Pool"?

**Comment by pinussilvestrus** [comment]
For me, it would be okay to stay with "Expanded Pool", it explains clear enough what will happen. An alternative would be maybe "Filled Pool" or "Create Process inside Pool".

**Comment by barmac** [comment]
How about a "Pool" without adjectives? If not that, then I would leave "Expanded Pool" as it is.

I just checked how Signavio solves that problem:

image

**Comment by pinussilvestrus** [comment]
Yeah, I already thought about the Signavio way of doing it. I think it's confusing if you have an Empty Pool and in the replace menu you just found the option "Pool". Because, technically, you already on a pool, but it's just empty. An adjective would be better here, "Expanded" might be good enough then.

**Review by barmac — APPROVED** [review]
🚀

**Pull request merged**
