### PR TITLE
deps: update to `diagram-js@13.8.0`

### PR DESCRIPTION
**Pull request by smbea**
feat: remove selection outline from connections (#826)
feat: position context pad according to last waypoint for connections (#826)

### CODE REVIEW

**Comment by smbea** [comment]
@philippfromme @barmac quick review here? 🙂

**Comment by barmac** [comment]
I am looking into this right now.

**Comment by barmac** [comment]
The grey rectangle strikes back:

https://github.com/bpmn-io/bpmn-js/assets/28307541/846b6fbe-13f5-43b5-ab53-1958d1b24970

**Comment by barmac** [comment]
Please disregard the comment above. I had an old branch on my machine.

**Review by barmac — APPROVED** [review]

**Pull request merged**
