### PR TITLE
fix(replace-menu): keep existing loop characteristics

### PR DESCRIPTION
**Pull request by philippfromme**
Partially addresses https://github.com/camunda/camunda-modeler/issues/4310.

brave_V1BCetnO9u

Related to https://github.com/camunda/camunda-modeler/issues/4310

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] **Brief textual description** of the changes present
* [x] **Visual demo** attached
* [ ] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by nikku** [comment]
@philippfromme Could you elaborate ("text") what part of the linked issue is tackled, and what part is not addressed (yet)?

**Review by nikku — COMMENTED** [review]
Requires test cases to verify this behavior.

**Review by nikku — CHANGES_REQUESTED** [review]
Needs test case to verify things work.

**Comment by nikku** [comment]
Is this fix here needed then? I assume yes, because also without `zeebe` stuff involved, we want to be forgiving (keep standard multi-instance loop properties, if possible)?

**Comment by philippfromme** [comment]
It's not strictly necessary but it avoids an unnecessary replacing of the `bpmn:MultiInstanceLoopCharacteristics` element.

**Comment by nikku** [comment]
Ok, happy to merge if we have another test case for this, facing a user relevant change.

**Comment by philippfromme** [comment]
Ok, will add.

**Comment by philippfromme** [comment]
Added test coverage via https://github.com/bpmn-io/bpmn-js/pull/2251/commits/bfa184b559d7f6cced7b5c85433e401a527fdad6.

**Comment by nikku** [comment]
Great stuff!

**Review by nikku — APPROVED** [review]

**Comment by nikku** [comment]
As good measure, already add a CHANGELOG entry to indicate this change.

**Pull request merged**
