### PR TITLE
deps: update to `bpmn-moddle@7.1.3`

### PR DESCRIPTION
**Pull request by barmac**

### CODE REVIEW

**Comment by barmac** [comment]
I don't know where the `const` failure comes from. Anyway, if we are releasing this with `bpmn-js@9.4.0`, I could as well target this at `develop`.

**Comment by barmac** [comment]
I missed https://github.com/bpmn-io/bpmn-js/pull/1726#issuecomment-1222147263, sorry.

**Comment by nikku** [comment]
[This](https://github.com/bpmn-io/bpmn-js/pull/1727/commits/5e554bae5bfcab64156a1dca2194aa069160dbc2) is where it is coming from.

**Comment by barmac** [comment]
Thanks Nico!

**Pull request merged**
