### PR TITLE
Use search

### PR DESCRIPTION
**Pull request by nikku**
### Proposed Changes

This plugs into the new `search` utility shipped with https://github.com/bpmn-io/diagram-js/pull/916 / [diagram-js@14.11.0](https://github.com/bpmn-io/diagram-js/blob/develop/CHANGELOG.md#14110), now updated and fixed via https://github.com/bpmn-io/diagram-js/pull/932:

capture iXVRwy_optimized

Try out via

```
npx @bpmn-io/sr bpmn-io/bpmn-js#use-search
```

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] **Brief textual description** of the changes present
* [x] **Visual demo** attached
* [x] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

---

Depends on https://github.com/bpmn-io/diagram-js/pull/932

### CODE REVIEW

**Comment by nikku** [comment]
Depends on https://github.com/bpmn-io/diagram-js/pull/932 to be fixed.

**Comment by nikku** [comment]
Also depends on / users would benefit from [restoring fuzzy search](https://github.com/bpmn-io/diagram-js/pull/932).

**Comment by lmbateman** [comment]
I'm not sure I understand the prior behavior and its problems well enough to comment. Any chance I could get a demo with some explanation? Thank you!

**Comment by nikku** [comment]
@lmbateman I'll give you a demo once I'm close to merging this, but it is important to me to mention you, so you're aware of UX improvement in search (popup menu, and global search).

**Comment by nikku** [comment]
Upstream fixes most described isses: https://github.com/bpmn-io/diagram-js/pull/932.

Try out the changes via 

```
npx @bpmn-io/sr bpmn-io/bpmn-js#use-search -l bpmn-io/diagram-js#fix-search
```

**Comment by nikku** [comment]
Previous observations, addressed by this PR as well as https://github.com/bpmn-io/diagram-js/pull/932:

---


Some observations:

* The search syntax and what is required by `search-pad` are incompatible, and require [manual conversion](https://github.com/bpmn-io/bpmn-js/compare/use-search?expand=1#diff-8a394357d479589cd4606da39fc67ac8ed374cc2803e5483f508239a88194ee9R72). This is inconvenient. I do regard the new format (`token = { value, matched: boolean }`) to be supperior. Maybe we could make `SearchPadProvider` compatible with it?

* `search` only returns tokens where they exist. This is inconvenient and requires me to manually check if tokens are return. Example: I test objects of the form `{ name: string }` for the key `label`, and expect the result to contain `{ tokens: { label: [ ... ] } }` regardless of whether any of the objects had a label property. Today, `undefined` is returned and [must be accounted for](https://github.com/bpmn-io/bpmn-js/compare/use-search?expand=1#diff-8a394357d479589cd4606da39fc67ac8ed374cc2803e5483f508239a88194ee9R103).

* We only return matched tokens, and do not return what did not match. This leads to changes in the output (it does no longer show previously visible information (i.e. the ID, whether or not it matched):

  capture wdEgza_optimized

Overall we can see that this is quite an improvement, removing the heavy matching / tokenization from implementors. Great job :medal_military:

**Review by philippfromme — APPROVED** [review]
Great stuff! Glad to see this in bpmn-js finally! 🥇

**Comment by tony2y** [comment]
How to use the search function? I have upgraded to the latest version。 @nikku @philippfromme

**Pull request merged**
