### PR TITLE
Space Tool Improvements 2/2

### PR DESCRIPTION
**Pull request by philippfromme**
brave_6IU2iiSBYb

brave_55pSWVSfCu

__Which issue does this PR address?__

* https://github.com/bpmn-io/diagram-js/pull/480
* do not resize text annotations when using the space tool

Closes https://github.com/bpmn-io/bpmn-js/issues/1302

Related to https://github.com/camunda/camunda-modeler/issues/1371
Related to https://github.com/camunda/camunda-modeler/issues/1705
Child of camunda/camunda-modeler#1753

Depends on https://github.com/bpmn-io/diagram-js/pull/480

### CODE REVIEW

**Comment by barmac** [comment]
Is it ready for review?

**Comment by philippfromme** [comment]
Yes, it is. It's part of this effort: https://github.com/camunda/camunda-modeler/issues/1753

**Review by barmac — CHANGES_REQUESTED** [review]
Regarding https://github.com/bpmn-io/bpmn-js/pull/1344/commits/737e38bffe2a9d35d78bc08f935fbd3044a94c60, we don't target features at the main branch. Let's maybe move it to a separate PR or just target the whole PR to `develop`?

For the label fix, I was surprised by this behaviour:
resize
I'd expect the label to not move at all if parent element is not affected.

**Review by nikku — CHANGES_REQUESTED** [review]
Generally this one looks pretty :cool:.

Found two last bugs :tm: that could be worth looking into:

capture o9u68c_optimized

----

UPDATE: Hold on, I may have messed up my dev setup here...

**Comment by philippfromme** [comment]
I fixed the issue with the attachers (https://github.com/bpmn-io/diagram-js/pull/480/commits/0476037c7a3c793061ded7515296d9dbe3d13f86). The issue with the visual is a minor inconvenience so I'd ignore it for now.

**Review by nikku — CHANGES_REQUESTED** [review]
Found one last bug (TM) (R).

capture FN64T4_optimized

Moved this issue to `backlog`. Would be nice to fix this thing, at last. On the other hand there is no urgency from my side to look into this.

**Comment by philippfromme** [comment]
Fixed the issue.

space

**Comment by nikku** [comment]
How?

**Comment by nikku** [comment]
What? Where is the test case that verifies the thing is fixed?

**Comment by philippfromme** [comment]
I've updated this commit to include the fix: https://github.com/bpmn-io/diagram-js/pull/480/commits/20c14a58d70a817b55a5ce971fb208323e0e5fe5

Here's the actual fix: https://github.com/bpmn-io/diagram-js/pull/480/commits/20c14a58d70a817b55a5ce971fb208323e0e5fe5#diff-e1f331de31685a3c3b785427b5dc5c2f9b4b877999e7ec88096eb8896c03182bR317

And here's the test: https://github.com/bpmn-io/diagram-js/pull/480/commits/20c14a58d70a817b55a5ce971fb208323e0e5fe5#diff-e018f0fd62502e40d89db1e2aec838cf64dfe97981c17fd0efcb508403b00aceR647

**Review by nikku — CHANGES_REQUESTED** [review]
This breaks adding new lanes:

capture cT7E6A_optimized

My proposal is: Do not update tests, as we fix things but rather add new tests. 

Have integration tests in bpmn-js that verify behaviors work.

**Comment by nikku** [comment]
Last bug.

capture ucOpl5_optimized

**Comment by philippfromme** [comment]
@barmac This is ready to be reviewed.

**Review by barmac — APPROVED** [review]

**Comment by philippfromme** [comment]
❤️

**Pull request merged**
