### PR TITLE
fix(modeling): update AddLaneHandler to new spaceTool API

### PR DESCRIPTION
**Pull request by nikku**
Related to https://github.com/camunda/camunda-modeler/issues/1715

### CODE REVIEW

**Comment by philippfromme** [comment]
One thing I've noticed is that labels are not moving anymore because they have to be added to the moving shapes explicitly.

Potential fix:

```
// (1) collect affected elements to create necessary space
  var allAffected = [];

  eachElement(lanesRoot, function(element) {
    allAffected.push(element);

   
    // FIX
    if (element.label) {
      allAffected.push(element.label);
    }

    if (element === shape) {
      return [];
    }

    return filter(element.children, function(c) {
      return c !== shape;
    });
  });
```

**Comment by nikku** [comment]
Note that https://github.com/bpmn-io/bpmn-js/pull/1287#issuecomment-596440376 would technically be fixed / was fixed by the old way the space tool worked (i.e. by automagically moving labels with space-moved shapes and connections, cf. https://github.com/camunda/camunda-modeler/issues/1705).

**Comment by nikku** [comment]
Will add a fix regardless so we have that case covered. How the label is being moved is an implementation detail, indeed.

**Comment by nikku** [comment]
Should be all fixed and :green_apple: now.

**Pull request merged**
