### PR TITLE
fix(modeling): attach shapes with labels on paste

### LINKED ISSUE #1204: Intermediate Events with labels cannot be pasted as Boundary Events
__Describe the Bug__

If an intermediate event has a label, it cannot be pasted as a boundary event. See the GIF:
bug

__Steps to Reproduce__

1. Create an intermediate event with label
2. Copy the event
3. Try to paste it over a Task, as a boundary event.

__Expected Behavior__

Intermediate Event can be pasted as Boundary Event

__Environment__

 - OS: Mac OS Mojave 10.14.5
 - Library version: v5.0.5

### PR DESCRIPTION
**Pull request by oguzeroglu**
Closes #1204

Related to https://github.com/bpmn-io/diagram-js/pull/413

This also fixes: #1205 however will do another PR for that issue to commit some tests.

Kapture 2019-10-02 at 14 44 51

### CODE REVIEW

**Comment by barmac** [comment]
`fix(CreateBoundaryEventBehavior)` => `fix(modeling)`

**Comment by barmac** [comment]
problem
This requires a fix.

**Comment by oguzeroglu** [comment]
@barmac Ready!

sdfdsf

asd

**Comment by barmac** [comment]
Accidentally merged to master while it depends on a future minor release of `diagram-js`.

**Pull request merged**
